-- INTER A to Z seed data (idempotent via INSERT IGNORE with explicit IDs)

-- 1) core_values
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (1, '선도적/정량 목표의식', 'target', '조직의 목표와 연계된 도전적인 목표를 설정하고, 선행·후행 지표를 수치화하여 목표 달성 과정을 체계적으로 관리합니다.', 1);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (2, '초효율적 시간관리', 'clock', 'AI 등 다양한 도구와 리소스를 적극 활용하여 업무를 자동화/효율화하고, 확보한 시간을 더 높은 가치의 업무에 집중하며 마감기한을 준수합니다.', 2);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (3, '집요한 끈기', 'repeat', '실패를 통해 빠르게 배우고 전략을 수정하며 반복적으로 실행합니다. 어려운 과제나 불확실한 상황에서도 끝까지 해결책을 찾아냅니다.', 3);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (4, '가치중심적 문제해결', 'bulb', '고객과 시장에 대한 깊은 이해를 바탕으로 문제의 본질을 파악하고, 단기적인 해결이 아닌 조직 차원의 구조적인 해결방안을 고민합니다.', 4);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (5, '근본적 비판 사고', 'brain', '수치와 데이터를 근거로 기존 방식과 경험을 비판적으로 돌아보고, 더 나은 전략과 근본적인 대안을 도출합니다.', 5);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (6, '혁신 프로세스 가속화', 'robot', 'AI와 새로운 기술을 적극 활용하여 업무 방식을 개선하고, 더 효율적인 프로세스를 제안하며 동료들과 함께 발전시켜 나갑니다.', 6);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (7, '최고수준의 결과지향', 'trophy', '반복적인 실수를 줄이고 높은 품질을 지속적으로 유지합니다. 맡은 결과물 하나하나에 최고 수준의 완성도와 전문성을 추구합니다.', 7);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (8, '자발적 성장동기', 'seeding', '자신의 일의 의미와 가치를 이해하고, 강박적 호기심을 바탕으로 스스로 성장하며 업무를 주도합니다.', 8);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (9, '미래낙관적 도전', 'rainbow', '예상치 못한 변화와 어려움 속에서도 낙천적인 태도를 유지합니다. 더 나은 미래를 믿고 새로운 도전을 이어가며 주변에도 긍정적인 에너지를 전합니다.', 9);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (10, '성장지향 피드백', 'message-circle-2', '피드백을 적극적으로 주고받으며, 열린 마음으로 수용하고 감사함을 표현합니다. 이를 통해 함께 성장하는 솔직한 소통 문화를 만들어갑니다.', 10);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (11, '관계기반 전략소통', 'users', '내·외부 이해관계자와 신뢰를 바탕으로 전략적 네트워크를 형성하며, 더 큰 시너지를 통한 새로운 기회를 창출합니다.', 11);
INSERT IGNORE INTO core_values (id, name, icon, description, sort_order) VALUES (12, '강박적 호기심', 'search', '새로운 분야에도 호기심을 가지고 끊임없이 질문하고 학습하며, 배운 내용을 실무에 적극 적용해 더 나은 방법을 찾아갑니다.', 12);

-- 2) value_cards (INTRO, SITUATION x2, QUIZ per core value)
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (1, 1, 'INTRO', '숫자로 말하는 목표, 그게 진짜 목표야 🎯', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (2, 1, 'SITUATION', '입사 첫 주, 팀장님이 ''이번 분기 목표가 뭐예요?'' 라고 묻는다. 막연히 ''열심히 하겠습니다''라고 답하려던 순간!', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (3, 1, 'SITUATION', '선배가 알려준 꿀팁: 선행지표(내가 통제 가능한 행동)와 후행지표(결과)를 같이 세우면, 목표가 흐지부지되지 않는다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (4, 1, 'QUIZ', '다음 중 ''선도적/정량 목표의식''에 가장 가까운 목표 설정은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (5, 2, 'INTRO', '시간은 아끼는 게 아니라 재설계하는 것 ⏱️', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (6, 2, 'SITUATION', '매주 반복되는 리포트 작성에 3시간씩 쓰고 있다. 마감은 다가오는데 이걸 계속 손으로 해야 할까?', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (7, 2, 'SITUATION', 'AI 도구로 반복 작업을 자동화한 동료는 그 시간에 더 중요한 전략 미팅에 참여하고 있다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (8, 2, 'QUIZ', '''초효율적 시간관리''를 가장 잘 실천한 행동은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (9, 3, 'INTRO', '실패는 데이터일 뿐, 끝은 아니다 🔥', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (10, 3, 'SITUATION', '런칭 D-3, 새벽 2시. 결제 API가 갑자기 죽었다. 사수는 퇴근했고 고객사 데모는 내일 오전 10시다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (11, 3, 'SITUATION', '3시간의 삽질 끝에 원인을 찾았다. 포기하지 않은 덕분에 데모는 예정대로 진행됐다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (12, 3, 'QUIZ', '이런 상황에서 ''집요한 끈기''에 가장 가까운 행동은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (13, 4, 'INTRO', '증상 말고 원인을 고쳐야 다시 안 아프다 💡', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (14, 4, 'SITUATION', '같은 고객 문의가 이번 달에만 세 번째 들어왔다. 매번 빠르게 응대만 해주고 넘어갔다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (15, 4, 'SITUATION', '문의 로그를 다시 보니, 사실 온보딩 가이드 자체가 헷갈리게 쓰여 있었다는 걸 발견했다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (16, 4, 'QUIZ', '''가치중심적 문제해결''에 가장 가까운 다음 행동은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (17, 5, 'INTRO', '''원래 이렇게 해왔어''는 이유가 아니다 🧠', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (18, 5, 'SITUATION', '3년째 똑같은 방식으로 진행하는 프로젝트 회의. 다들 당연하게 여기지만 최근 성과 지표는 계속 하락 중이다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (19, 5, 'SITUATION', '데이터를 뜯어보니, 이 방식이 오히려 병목이었다는 게 드러났다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (20, 5, 'QUIZ', '''근본적 비판 사고''를 가장 잘 보여주는 태도는?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (21, 6, 'INTRO', '어제의 프로세스가 오늘도 최선일 필요는 없다 🤖', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (22, 6, 'SITUATION', '팀에서 여전히 수작업으로 데이터를 취합하고 있다. 매주 반나절이 여기에 들어간다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (23, 6, 'SITUATION', 'AI 자동화 도구를 팀에 제안했더니, 이제 그 시간에 다들 더 중요한 일을 한다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (24, 6, 'QUIZ', '''혁신 프로세스 가속화''에 해당하는 행동은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (25, 7, 'INTRO', '''대충 완료''와 ''진짜 완성''은 다르다 🏆', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (26, 7, 'SITUATION', '마감이 30분 남았다. 보고서는 얼추 완성됐지만 오탈자와 데이터 오차가 조금 남아있다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (27, 7, 'SITUATION', '꼼꼼히 다시 검토한 덕분에, 이번엔 팀장님께 별도 수정 요청 없이 바로 통과했다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (28, 7, 'QUIZ', '''최고수준의 결과지향''에 가장 가까운 태도는?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (29, 8, 'INTRO', '시켜서 하는 일과 하고 싶어서 하는 일의 차이 🌱', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (30, 8, 'SITUATION', '회사에서 특별히 시키지 않은 툴이 있는데, 배워두면 앞으로 업무에 도움이 될 것 같다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (31, 8, 'SITUATION', '주말에 스스로 공부해서 익힌 스킬을 다음 프로젝트에 바로 적용해봤다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (32, 8, 'QUIZ', '''자발적 성장동기''를 가장 잘 보여주는 행동은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (33, 9, 'INTRO', '흐린 날에도 다음 맑음을 믿는 사람 🌈', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (34, 9, 'SITUATION', '야심 차게 준비한 프로젝트가 갑자기 방향이 바뀌었다. 팀 분위기가 순식간에 가라앉았다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (35, 9, 'SITUATION', '한 동료가 ''이번에 배운 것도 다음 기회의 자산이 될 거예요''라며 팀 분위기를 다시 끌어올렸다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (36, 9, 'QUIZ', '''미래낙관적 도전''에 가장 가까운 반응은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (37, 10, 'INTRO', '쓴소리도 선물이 될 수 있다 💬', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (38, 10, 'SITUATION', '사수가 내가 만든 자료에 대해 꽤 직설적인 피드백을 줬다. 처음엔 조금 서운했다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (39, 10, 'SITUATION', '곰곰이 생각해보니 다 맞는 말이었고, 다음 자료는 훨씬 좋아졌다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (40, 10, 'QUIZ', '''성장지향 피드백''을 가장 잘 실천하는 태도는?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (41, 11, 'INTRO', '신뢰는 필요할 때 갑자기 생기지 않는다 🤝', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (42, 11, 'SITUATION', '다른 팀과 협업할 일이 생겼는데, 평소 교류가 없어서 어색하게 업무 요청만 오간다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (43, 11, 'SITUATION', '평소 스몰토크와 정보 공유로 관계를 쌓아온 동료는 다른 팀에서도 도움을 술술 받는다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (44, 11, 'QUIZ', '''관계기반 전략소통''에 가장 가까운 행동은?', 4);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (45, 12, 'INTRO', '질문이 많은 사람이 결국 더 멀리 간다 🔍', 1);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (46, 12, 'SITUATION', '회의에서 낯선 용어가 나왔다. 다들 아는 척 넘어가는 분위기다.', 2);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (47, 12, 'SITUATION', '용기 내어 질문했더니, 사실 절반은 정확히 모르고 있었다는 게 드러났고 다 같이 배웠다.', 3);
INSERT IGNORE INTO value_cards (id, core_value_id, card_type, content, sort_order) VALUES (48, 12, 'QUIZ', '''강박적 호기심''을 가장 잘 보여주는 행동은?', 4);

-- 3) quiz_options
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (1, 4, '이번 분기 매출을 3억 늘린다 (선행지표: 주 20건 고객 미팅)', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (2, 4, '열심히 최선을 다해서 좋은 결과를 낸다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (3, 4, '팀장님이 시키는 대로 한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (4, 4, '남들 하는 만큼만 한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (5, 8, '반복 리포트를 AI로 자동화하고, 확보한 시간을 전략 업무에 쓴다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (6, 8, '야근을 해서라도 모든 걸 손으로 다 처리한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (7, 8, '마감을 살짝 넘기더라도 완벽하게 만든다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (8, 8, '새로운 도구는 배우기 귀찮으니 안 쓴다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (9, 12, '포기하지 않고 원인을 끝까지 찾되, 필요하면 도움도 요청한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (10, 12, '바로 데모를 취소한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (11, 12, '혼자 끙끙 앓다가 아무에게도 알리지 않는다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (12, 12, '내일 출근해서 생각한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (13, 16, '가이드 문서 자체를 개선해서 근본 원인을 없앤다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (14, 16, '네 번째 문의가 올 때까지 기다린다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (15, 16, '고객에게 알아서 검색해보라고 안내한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (16, 16, '매번 똑같이 빠르게 답만 해준다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (17, 20, '데이터를 근거로 기존 방식에 의문을 제기하고 대안을 제안한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (18, 20, '선배들이 해온 방식이니 그냥 따른다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (19, 20, '문제를 알지만 굳이 말하지 않는다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (20, 20, '감으로 다른 방식을 시도해본다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (21, 24, '비효율적인 프로세스를 AI/신기술로 개선하자고 팀에 제안한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (22, 24, '불편해도 원래 하던 대로만 한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (23, 24, '나 혼자만 몰래 효율화 도구를 쓴다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (24, 24, '새 기술은 리스크가 크니 시도하지 않는다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (25, 28, '시간이 촉박해도 마지막까지 품질을 점검하고 제출한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (26, 28, '일단 제출하고 지적받으면 그때 고친다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (27, 28, '오탈자 정도는 늘 있는 일이니 신경 안 쓴다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (28, 28, '품질보다 속도가 항상 우선이다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (29, 32, '시키지 않아도 필요하다고 판단되면 스스로 학습하고 적용한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (30, 32, '회사가 교육을 시켜줄 때까지 기다린다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (31, 32, '당장 필요 없으면 절대 배우지 않는다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (32, 32, '배운 걸 실무에 적용하지 않고 묵혀둔다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (33, 36, '변화를 배움의 기회로 받아들이고 팀에 긍정적인 에너지를 전한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (34, 36, '바뀐 방향에 대해 계속 불평만 한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (35, 36, '의욕을 잃고 최소한의 일만 한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (36, 36, '팀 분위기가 가라앉아도 신경 쓰지 않는다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (37, 40, '피드백을 열린 마음으로 받아들이고 감사를 표현한 뒤 반영한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (38, 40, '피드백을 받으면 방어적으로 반박부터 한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (39, 40, '기분 나쁘니 앞으로 피드백을 피한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (40, 40, '동료에게는 피드백을 절대 주지 않는다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (41, 44, '평소에 내외부 이해관계자와 신뢰를 쌓아두고 필요할 때 시너지를 만든다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (42, 44, '필요할 때만 연락하고 평소엔 교류하지 않는다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (43, 44, '협업은 번거로우니 최대한 피한다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (44, 44, '내 팀 일만 신경 쓰면 충분하다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (45, 48, '모르는 걸 그냥 넘기지 않고 질문해서 배우고 실무에 적용한다', 1);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (46, 48, '모르는 척 티 안 나게 그냥 넘어간다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (47, 48, '나중에 혼자 찾아보고 아무에게도 안 알린다', 0);
INSERT IGNORE INTO quiz_options (id, card_id, text, is_correct) VALUES (48, 48, '새로운 분야는 어차피 안 쓸 거라 무시한다', 0);

-- 4) badges: 12 per-value badges (id = core_value id), streak badges, all-clear badge
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (1, '선도적/정량 목표의식 마스터', 'target', 'VALUE_COMPLETE', 1);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (2, '초효율적 시간관리 마스터', 'clock', 'VALUE_COMPLETE', 2);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (3, '집요한 끈기 마스터', 'repeat', 'VALUE_COMPLETE', 3);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (4, '가치중심적 문제해결 마스터', 'bulb', 'VALUE_COMPLETE', 4);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (5, '근본적 비판 사고 마스터', 'brain', 'VALUE_COMPLETE', 5);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (6, '혁신 프로세스 가속화 마스터', 'robot', 'VALUE_COMPLETE', 6);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (7, '최고수준의 결과지향 마스터', 'trophy', 'VALUE_COMPLETE', 7);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (8, '자발적 성장동기 마스터', 'seeding', 'VALUE_COMPLETE', 8);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (9, '미래낙관적 도전 마스터', 'rainbow', 'VALUE_COMPLETE', 9);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (10, '성장지향 피드백 마스터', 'message-circle-2', 'VALUE_COMPLETE', 10);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (11, '관계기반 전략소통 마스터', 'users', 'VALUE_COMPLETE', 11);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (12, '강박적 호기심 마스터', 'search', 'VALUE_COMPLETE', 12);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (13, '7일 연속 스트릭', 'flame', 'STREAK', 7);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (14, '14일 연속 스트릭', 'flame', 'STREAK', 14);
INSERT IGNORE INTO badges (id, name, icon, condition_type, condition_value) VALUES (15, '12가치 올클리어', 'award', 'ALL_VALUES', 12);

-- 5) sample weekly missions
INSERT IGNORE INTO missions (id, week_number, title, description, related_core_value_id, created_by) VALUES (1, 1, '사수에게 자기소개 메시지 보내기', '사수와 팀원들에게 나를 소개하는 메시지를 보내보세요. 관계기반 전략소통의 첫걸음입니다.', 11, NULL);
INSERT IGNORE INTO missions (id, week_number, title, description, related_core_value_id, created_by) VALUES (2, 1, '이번주 목표 1개 수치화해서 적어보기', '이번 주 내가 달성하고 싶은 목표를 선행지표/후행지표로 나눠 적어보세요.', 1, NULL);
INSERT IGNORE INTO missions (id, week_number, title, description, related_core_value_id, created_by) VALUES (3, 2, '반복 업무 1개를 AI로 자동화해보기', '매주 반복하는 업무 중 하나를 골라 AI 도구로 자동화하는 방법을 찾아 시도해보세요.', 2, NULL);
INSERT IGNORE INTO missions (id, week_number, title, description, related_core_value_id, created_by) VALUES (4, 2, '동료에게 감사 피드백 남기기', '함께 일한 동료에게 구체적인 감사 피드백을 남겨보세요.', 10, NULL);
